### ISSUE TITLE
Firmware info

### ISSUE THREAD

**Issue by leroyloren** [mjmccans/hassio-addon-airthings#11]
Would it be possible to display device firmware information please?

For example:
![obrazek](https://user-images.githubusercontent.com/57643470/164730864-452e99c1-81a8-4a36-96d7-40665beab1b0.png)

App:
![obrazek](https://user-images.githubusercontent.com/57643470/164730967-4327cd54-66cc-4e31-b0e1-3ebad02814c8.png)

**Comment by mjmccans** [comment]
Thank you for this suggestion. I have taken a quick look and the serial number is not something that is currently being decoded from the output from the devices. However, when I have a bit more time I will dig in a bit more and see if I can figure out how to get the firmware information.

**Comment by mjmccans** [comment]
It took a while, but the latest version of the add-on that I just published does include the firmware version as reported by the device. It doesn't look quite like it does in the Airthings App so this may not be a full answer to your request, but hopefully it helps.
