### ISSUE TITLE
Stop button lost

### ISSUE THREAD

**Issue by uowis** [mjmccans/hassio-addon-airthings#13]
Peraphs it's since Hass upgrade, i have lost Stop and restart button of add-on and the add-on is stuck
When i try to call service restart, start or stop add-on, nothing happens

`Home Assistant Supervisor: Stop add-on`

There is no error in log
```
Home Assistant Core 2022.6.2
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.1
```

**Comment by uowis** [comment]
I had this bug two time it disappeared only with  host reboot.

**Comment by mjmccans** [comment]
Happy to hear that you have fixed your problem, but this would not have been an issue with the addon. The addon has no control over those interface elements, but sometimes those kinds of things can happen after an update and can be fixed by clearing your browser cache or restarting Home Assistant.

**Comment by uowis** [comment]
This bug come back offen and force me to reboot host device. I have no error, no log nothing but integration don"t want to sart ,... That why don't have stop and restart buttun,.. 
I believe i can try to run integration in cmmand line but i don"t found it.
