### ISSUE TITLE
Airthings ble for view plus

### ISSUE THREAD

**Issue by estofira** [mjmccans/hassio-addon-airthings#24]
Its rather a question then an issue : is it possible/planned to pull data from view plus via ble ?
A had a view plus and dont like the cloud way of pulling data from it

**Comment by mjmccans** [comment]
Unfortunately I do not have that model so I cannot do any testing, and it is not clear to me from the product specifications if the View devices provide access to the sensor data via ble (the specifications suggest that bluetooth is only for on-boarding and setup). In addition, support for Airthings devices via bluetooth has now been integrated into Home Assistant Core, so this add-on is not really being used anymore. Your best bet may be open an issue in the [Home Assistant Core repository](https://github.com/home-assistant/core/issues), and mention the integration "airthings_ble". Sorry to not be able to provide more help.
