### ISSUE TITLE
WARNINGS in the  HA log

### ISSUE THREAD

**Issue by def1149** [mjmccans/hassio-addon-airthings#25]
The following appears over and over in the HA LOG

Logger: homeassistant.components.mqtt.mixins
Source: components/mqtt/mixins.py:1206
Integration: MQTT (documentation, issues)
First occurred: 10:36:56 AM (9 occurrences)
Last logged: 10:36:56 AM

MQTT entity name starts with the device name in your config {'name': 'Airthings Wave+ Radon (longterm avg.)', 'icon': 'mdi:radioactive', 'state_class': <SensorStateClass.MEASUREMENT: 'measurement'>, 'unit_of_measurement': 'Bq/m3', 'unique_id': 'xx:xx:xx:xx:xx:xx_radon_longterm_avg', 'state_topic': 'airthings/xx:xx:xx:xx:xx:xx/radon_longterm_avg', 'device': {'connections': [['mac', 'xx:xx:xx:xx:xx:xx']], 'identifiers': ['185649'], 'manufacturer': 'Airthings AS', 'name': 'Airthings Wave+', 'model': '2930', 'sw_version': 'G-BLE-2.2.0-master+0'}, 'availability_mode': 'latest', 'enabled_by_default': True, 'qos': 0, 'encoding': 'utf-8', 'payload_available': 'online', 'payload_not_available': 'offline', 'force_update': False}, this is not expected. Please correct your configuration. The device name prefix will be stripped off the entity name and becomes 'Radon (longterm avg.)'
MQTT entity name starts with the device name in your config {'name': 'Airthings Wave+ Temperature', 'device_class': <SensorDeviceClass.TEMPERATURE: 'temperature'>, 'state_class': <SensorStateClass.MEASUREMENT: 'measurement'>, 'unit_of_measurement': '°C', 'unique_id': 'xx:xx:xx:xx:xx:xx_temperature', 'state_topic': 'airthings/xx:xx:xx:xx:xx:xx/temperature', 'device': {'connections': [['mac', 'xx:xx:xx:xx:xx:xx']], 'identifiers': ['185649'], 'manufacturer': 'Airthings AS', 'name': 'Airthings Wave+', 'model': '2930', 'sw_version': 'G-BLE-2.2.0-master+0'}, 'availability_mode': 'latest', 'enabled_by_default': True, 'qos': 0, 'encoding': 'utf-8', 'payload_available': 'online', 'payload_not_available': 'offline', 'force_update': False}, this is not expected. Please correct your configuration. The device name prefix will be stripped off the entity name and becomes 'Temperature'
MQTT entity name starts with the device name in your config {'name': 'Airthings Wave+ Pressure', 'device_class': <SensorDeviceClass.PRESSURE: 'pressure'>, 'state_class': <SensorStateClass.MEASUREMENT: 'measurement'>, 'unit_of_measurement': 'mbar', 'unique_id': 'xx:xx:xx:xx:xx:xx_rel_atm_pressure', 'state_topic': 'airthings/xx:xx:xx:xx:xx:xx/rel_atm_pressure', 'device': {'connections': [['mac', 'xx:xx:xx:xx:xx:xx']], 'identifiers': ['185649'], 'manufacturer': 'Airthings AS', 'name': 'Airthings Wave+', 'model': '2930', 'sw_version': 'G-BLE-2.2.0-master+0'}, 'availability_mode': 'latest', 'enabled_by_default': True, 'qos': 0, 'encoding': 'utf-8', 'payload_available': 'online', 'payload_not_available': 'offline', 'force_update': False}, this is not expected. Please correct your configuration. The device name prefix will be stripped off the entity name and becomes 'Pressure'
MQTT entity name starts with the device name in your config {'name': 'Airthings Wave+ CO2', 'device_class': <SensorDeviceClass.CO2: 'carbon_dioxide'>, 'icon': 'mdi:molecule-co2', 'state_class': <SensorStateClass.MEASUREMENT: 'measurement'>, 'unit_of_measurement': 'ppm', 'unique_id': 'xx:xx:xx:xx:xx:xx_co2', 'state_topic': 'airthings/xx:xx:xx:xx:xx:xx/co2', 'device': {'connections': [['mac', 'xx:xx:xx:xx:xx:xx']], 'identifiers': ['185649'], 'manufacturer': 'Airthings AS', 'name': 'Airthings Wave+', 'model': '2930', 'sw_version': 'G-BLE-2.2.0-master+0'}, 'availability_mode': 'latest', 'enabled_by_default': True, 'qos': 0, 'encoding': 'utf-8', 'payload_available': 'online', 'payload_not_available': 'offline', 'force_update': False}, this is not expected. Please correct your configuration. The device name prefix will be stripped off the entity name and becomes 'CO2'
MQTT entity name starts with the device name in your config {'name': 'Airthings Wave+ VOC', 'icon': 'mdi:cloud', 'state_class': <SensorStateClass.MEASUREMENT: 'measurement'>, 'unit_of_measurement': 'ppb', 'unique_id': 'xx:xx:xx:xx:xx:xx_voc', 'state_topic': 'airthings/xx:xx:xx:xx:xx:xx/voc', 'device': {'connections': [['mac', 'xx:xx:xx:xx:xx:xx']], 'identifiers': ['185649'], 'manufacturer': 'Airthings AS', 'name': 'Airthings Wave+', 'model': '2930', 'sw_version': 'G-BLE-2.2.0-master+0'}, 'availability_mode': 'latest', 'enabled_by_default': True, 'qos': 0, 'encoding': 'utf-8', 'payload_available': 'online', 'payload_not_available': 'offline', 'force_update': False}, this is not expected. Please correct your configuration. The device name prefix will be stripped off the entity name and becomes 'VOC'

**Comment by mjmccans** [comment]
Thank you for submitting your issue. I have not updated this add-on for quite some time because local access for Airthings devices by BTLE was moved to Home Assistant Core so this add-on is no longer needed. This repository is really only here for historic reasons, although I probably should add a warning to the project description. Please try using the built-in integration and hopefully it will work well for you (I have been using it since its release without issue).
