### ISSUE TITLE
Connectivity Issues/Sync

### ISSUE THREAD

**Issue by loca5790** [mjmccans/hassio-addon-airthings#3]
I keep having the sensor data freezing on updating.  No error codes the values just get stuck and act as normal reporting in the log. 

There will be a message request saying failed and it retries but every retry is "successful" but it is repeating the exact same values for days.

When restarting the following will appear.

"2022-02-12 22:35:41] ERROR: Disconnected
Traceback (most recent call last):
  File "/src/airthings.py", line 229, in get_info
    char = self._dev.getCharacteristics(uuid=characteristic.uuid)[0]
  File "/usr/local/lib/python3.9/dist-packages/bluepy/btle.py", line 508, in getCharacteristics
    rsp = self._getResp('find')
  File "/usr/local/lib/python3.9/dist-packages/bluepy/btle.py", line 407, in _getResp
    resp = self._waitResp(wantType + ['ntfy', 'ind'], timeout)
  File "/usr/local/lib/python3.9/dist-packages/bluepy/btle.py", line 362, in _waitResp
    raise BTLEDisconnectError("Device disconnected", resp)
bluepy.btle.BTLEDisconnectError: Device disconnected"

After some failures connecting it will successfully connect pull new data then freeze at that same value.

**Comment by mjmccans** [comment]
Sorry that you are having problems with the addon. I can look into this a bit more, but I may need some additional information to be able to figure this out. Can you please set your log_level to "DEBUG" in your config and then send the output that you get when the data seems to freeze? Also, how far away is the Airthings device from the machine trying to read it? It would be interesting if when it does freeze you try moving the Airthings device closer for better reception and see if that does anything. Thank you.

**Comment by loca5790** [comment]
It's working again... I did set the log up to debug and it hasn't dropped out again in 15+ hours, it's me.

One of them is within 16 inches of the Pi4.  They sit next to each other on a shelf.  The ironic thing is the closest one was the one dropping out.  The one through 2 walls and 15 feet away was fine.

I appreciate you!

**Comment by mjmccans** [comment]
Happy to hear that it is working again. I am by no means an expert, but I understand that sometimes with radio devices there can be issues if they are too close together. I am going to close this issue but let me know if you have any other problems.

**Comment by loca5790** [comment]
Thank you, I'm learning as well.  Ironic that when the airthings came back on line my Aqara sensors dropped out.... at the same time.  I've been having issues back and forth I'm wondering if they are competing the same channel.  I just started a channel monitor and hopefully will catch it.

**Comment by loca5790** [comment]
@mjmccans   I think I figured it out.  It disconnected again on restart.  I opened the app and force synced my devices to my phone and they woke back up and started updating again.

It seems as if they are not waking up or establishing the first connection but once they are synced at the same time I do a request form the app they connect.
