### ISSUE TITLE
Missing documentation related to MQTT requirement/dependency

### ISSUE THREAD

**Issue by Givemeurcookies** [mjmccans/hassio-addon-airthings#9]
Thanks for writing the plugin! 

Just wanted to say that the requirements is missing having to set up a MQTT broker and MQTT add-on. It's not installed by default by Hassio and the documentation kind of seems to assume it's an internal MQTT broker that's installed by default.

If you try to run the addon without a MQTT broker and MQTT add-on you will get an error about missing parameters which isn't super descriptive.

**Comment by mjmccans** [comment]
Thank you for pointing this out. You are actually the second person to point out this error, so I have updated the documentation to include the MQTT Broker Addon as a requirement and have also added a check and a more descriptive error message if the addon is started without the MQTT Broker Addon running. Much appreciated!
